# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0eecc1c61842e94d06564ed5f94e82a272402629a0f8ad7835bb7c81412c6d393f2e5d1a27ef5bfe37aef80e7f8926cae6f548372c366c0e16405324219a676f

test:
  secret_key_base: 3f4587fd122c5ce40eb79447646053219c9f7746d78d3888179a37ace2083bf6a6f5cb4ba2b9c8f701e7f1cb811fe2d46c5428e4f4648febb6b74050a1d5ea68

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
